#ifndef PREDEFINEDVALUES_H
#define PREDEFINEDVALUES_H

#define DIRT_SELECTIONBUF_MIN_DUPES 10
#define DIRT_SELECTIONBUF_MIN_SIZE 512
#define DIRT_ENTRYBUFFER_SIZE 128
#define DIRT_CURSORINDICES_MIN_DUPES 10
#define DIRT_CURSORINDICES_MIN_SIZE 100
#define DIRT_N_SCREENS 9

#define DIRT_STATE_MAIN 1
#define DIRT_STATE_VOLUME 2
#define DIRT_STATE_PROMPT 3

#endif // PREDEFINEDVALUES_H
