#ifndef PREDEFINEDVALUES_H
#define PREDEFINEDVALUES_H

#define DIRT_SELECTIONBUF_MIN_DUPES 10
#define DIRT_SELECTIONBUF_MIN_SIZE 512
#define DIRT_ENTRYBUFFER_SIZE 128
#define DIRT_CURSORINDICES_MIN_DUPES 10
#define DIRT_CURSORINDICES_MIN_SIZE 32
#define DIRT_N_SCREENS 9

#endif // PREDEFINEDVALUES_H
